import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Study Spark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Navbar />
          <main className="flex-1 pl-58">{children}</main>
        </div>
      </body>
    </html>
  );
}
